method: grid
metric:
  goal: minimize
  name: Eval_Loss/Task5
parameters:
  baseline:
    value: lora
  epoch:
    value: 15
  finetune_type:
    value: train_mergeratioW_optHype_signMerge
  ft_task:
    value: 5
  lr:
    value: 1e-5
  hyperparameter_tune:
    value: True
  idrandom:
    value: 0
  mergeratio_lr:
    values: [1e-5, 3e-5, 5e-5, 7e-5, 9e-5, 1e-4, 3e-4, 5e-4, 7e-4, 9e-4, 1e-3, 3e-3, 5e-3, 7e-3, 9e-3, 1e-2]
  max_seq_length:
    value: 164
  ntasks:
    value: 6
  pt_task:
    value: 5
  seed:
    value: 2021
  ngpu:
    value: 4
  per_device_train_batch_size:
    value: 16
  learning_rate:
    value: 5e-4
program: finetune.py
name: WsignMerge CAM